steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/sms-gpt-373620/sms-gpt", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sms-gpt-373620/sms-gpt"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "sms-gpt",
        "--image",
        "gcr.io/sms-gpt-373620/sms-gpt",
        "--region",
        "us-central1",
        "--port",
        "5000",
      ]
images:
  - gcr.io/sms-gpt-373620/sms-gpt
